/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/lib/shadcn/ui/badge/Badge.vue')['default']
    Booking: typeof import('./src/domains/booking/pages/Booking/Booking.vue')['default']
    BookingCalendar: typeof import('./src/domains/booking/pages/BookingCalendar/BookingCalendar.vue')['default']
    BookingCalendarTemplate: typeof import('./src/domains/booking/templates/BookingCalendarTemplate/BookingCalendarTemplate.vue')['default']
    BookingCard: typeof import('./src/domains/booking/components/BookingCard/BookingCard.vue')['default']
    BookingHeader: typeof import('./src/domains/booking/components/BookingHeader/BookingHeader.vue')['default']
    BookingLayout: typeof import('./src/domains/booking/components/BookingLayout/BookingLayout.vue')['default']
    BookingOverview: typeof import('./src/domains/booking/pages/BookingOverview/BookingOverview.vue')['default']
    BookingOverviewTemplate: typeof import('./src/domains/booking/templates/BookingOverviewTemplate/BookingOverviewTemplate.vue')['default']
    BookingRoom: typeof import('./src/domains/booking/components/BookingRoom/RoomCard.vue')['default']
    Button: typeof import('./src/lib/shadcn/ui/button/Button.vue')['default']
    Calendar: typeof import('./src/domains/booking/components/Calendar/Calendar.vue')['default']
    Card: typeof import('./src/lib/shadcn/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/lib/shadcn/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/lib/shadcn/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/lib/shadcn/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/lib/shadcn/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/lib/shadcn/ui/card/CardTitle.vue')['default']
    DataProvider: typeof import('./src/domains/functional/components/DataProvider/DataProvider.vue')['default']
    DataProviderError: typeof import('./src/domains/functional/components/DataProvider/DataProviderError.vue')['default']
    DataProviderLoading: typeof import('./src/domains/functional/components/DataProvider/DataProviderLoading.vue')['default']
    Equipment: typeof import('./src/domains/booking/components/Equipment/Equipment.vue')['default']
    EquipmentGrid: typeof import('./src/domains/booking/components/EquipmentGrid/EquipmentGrid.vue')['default']
    Heading: typeof import('./src/domains/functional/components/Heading/Heading.vue')['default']
    Icon: typeof import('./src/domains/functional/components/Icon/Icon.vue')['default']
    Label: typeof import('./src/lib/shadcn/ui/label/Label.vue')['default']
    Room: typeof import('./src/domains/booking/pages/Room/Room.vue')['default']
    RoomCard: typeof import('./src/domains/booking/components/RoomCard/RoomCard.vue')['default']
    RoomGrid: typeof import('./src/domains/booking/components/RoomGrid/RoomGrid.vue')['default']
    RoomTemplate: typeof import('./src/domains/booking/templates/RoomTemplate/RoomTemplate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/lib/shadcn/ui/switch/Switch.vue')['default']
    Text: typeof import('./src/domains/functional/components/Text/Text.vue')['default']
    User: typeof import('./src/domains/user/pages/User/User.vue')['default']
    UserAside: typeof import('./src/domains/user/components/UserAside/UserAside.vue')['default']
    UserAvatar: typeof import('./src/domains/user/components/UserAvatar/UserAvatar.vue')['default']
    UserBookings: typeof import('./src/domains/user/components/UserBookings/UserBookings.vue')['default']
    UserHeader: typeof import('./src/domains/user/components/UserHeader/UserHeader.vue')['default']
  }
}
