/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/lib/shadcn/ui/badge/Badge.vue')['default']
    Button: typeof import('./src/lib/shadcn/ui/button/Button.vue')['default']
    Card: typeof import('./src/lib/shadcn/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/lib/shadcn/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/lib/shadcn/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/lib/shadcn/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/lib/shadcn/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/lib/shadcn/ui/card/CardTitle.vue')['default']
    ChartCrosshair: typeof import('./src/lib/shadcn/ui/chart/ChartCrosshair.vue')['default']
    ChartLegend: typeof import('./src/lib/shadcn/ui/chart/ChartLegend.vue')['default']
    ChartSingleTooltip: typeof import('./src/lib/shadcn/ui/chart/ChartSingleTooltip.vue')['default']
    ChartTooltip: typeof import('./src/lib/shadcn/ui/chart/ChartTooltip.vue')['default']
    DataProvider: typeof import('./src/domains/functional/components/DataProvider/DataProvider.vue')['default']
    DataProviderError: typeof import('./src/domains/functional/components/DataProvider/DataProviderError.vue')['default']
    DataProviderLoading: typeof import('./src/domains/functional/components/DataProvider/DataProviderLoading.vue')['default']
    Heading: typeof import('./src/domains/functional/components/Heading/Heading.vue')['default']
    Icon: typeof import('./src/domains/functional/components/Icon/Icon.vue')['default']
    Label: typeof import('./src/lib/shadcn/ui/label/Label.vue')['default']
    RoomBooking: typeof import('./src/domains/roomBooking/pages/RoomBooking/RoomBooking.vue')['default']
    RoomBookingLayout: typeof import('./src/domains/roomBooking/components/RoomBookingLayout/RoomBookingLayout.vue')['default']
    RoomBookingOverview: typeof import('./src/domains/roomBooking/pages/RoomBookingOverview/RoomBookingOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/lib/shadcn/ui/switch/Switch.vue')['default']
    User: typeof import('./src/domains/user/pages/User/User.vue')['default']
  }
}
